# TUGAS

## 1. Ikuti semua tahapan dalam modul ini.


## 1. Import Library dan Load Dataset Iris

Pada praktikum ini digunakan dataset Iris untuk mencoba algoritma Naïve Bayes. Pada tahap awal, library yang diperlukan diimport terlebih dahulu, kemudian dataset Iris diambil dari Scikit-Learn.

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
# Load dataset Iris dari scikit-learn
iris = load_iris()

## 2. Mengubah Dataset Menjadi DataFrame

Dataset Iris yang sudah diambil kemudian diubah ke dalam bentuk DataFrame menggunakan Pandas. Setelah itu ditambahkan kolom Species sebagai target atau label dari setiap data.

In [2]:
# Konversi data menjadi DataFrame Pandas
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df["Species"] = iris.target_names[iris.target]
# Definisikan X (fitur) dan y (target/label)
X = df.drop(columns=["Species"])
y = df["Species"]
print(X)

     sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]


## 3. Melihat Data Target

Variabel `y` digunakan untuk melihat target atau label dari dataset Iris. Data target terdiri dari tiga spesies, yaitu setosa, versicolor, dan virginica.

In [12]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 4. Mengubah Label Menjadi Data Numerik

Label spesies yang masih berbentuk teks diubah menjadi angka menggunakan `LabelEncoder`. Dengan cara ini, setiap kelas akan mempunyai nilai numerik yang bisa digunakan dalam proses klasifikasi.

In [4]:
from sklearn.preprocessing import LabelEncoder
lab = LabelEncoder()
y = lab.fit_transform(y)
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## 5. Membagi Data Training dan Testing

Data Iris kemudian dibagi menjadi data training dan data testing. Data training digunakan untuk melatih model, sedangkan data testing digunakan untuk menguji hasil prediksi model.

In [5]:
from sklearn.model_selection import train_test_split
X_train, X_test = train_test_split(X, test_size=0.2, random_state=0)
y_train, y_test = train_test_split(y, test_size=0.2, random_state=0)

## 6. Menentukan Gaussian Naïve Bayes

Dataset Iris memiliki fitur berupa data numerik kontinu, seperti panjang dan lebar sepal serta petal. Karena jenis datanya berupa angka kontinu, pada praktikum ini digunakan Gaussian Naïve Bayes.

In [6]:
from sklearn.naive_bayes import GaussianNB
model = GaussianNB()
NB_model = model.fit(X_train, y_train)

## 7. Melakukan Prediksi Data Testing

Setelah model selesai dilatih, model digunakan untuk melakukan prediksi terhadap data testing. Hasil prediksi disimpan pada variabel `result`.

In [7]:
result = NB_model.predict(X_test)
result

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0])

## 8. Menghitung Accuracy

Setelah mendapatkan hasil prediksi, dilakukan perhitungan accuracy untuk melihat seberapa banyak data testing yang berhasil diprediksi dengan benar oleh model.

In [8]:
from sklearn.metrics import accuracy_score
print('Accuracy of data testing: ', accuracy_score(y_test, result)*100)

Accuracy of data testing:  96.66666666666667


## 9. Melakukan Prediksi untuk Data Baru

Selain data testing, model juga dapat digunakan untuk memprediksi data baru. Pada tahap ini diberikan satu input baru yang memiliki empat nilai fitur seperti pada dataset Iris.

In [9]:
#prediksi inputan data baru
#input_data = pd.DataFrame(np.array([[5.1, 3.5, 1.4, 0.2]]), columns=iris.feature_names)
input_data = [[5.1, 3.5, 1.4, 0.2]]
result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)
print('Hasil prediksi untuk input baru adalah:', prediction_label)

Hasil prediksi untuk input baru adalah: ['setosa']


c:\Users\Brahmana P\AppData\Local\Programs\Python\Python314\Lib\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


## 10. Mengatasi Warning pada Prediksi Data Baru

Pada percobaan sebelumnya muncul warning karena model dilatih menggunakan DataFrame yang memiliki nama kolom, sedangkan input baru diberikan dalam bentuk list atau array tanpa nama kolom. Supaya format input sama dengan data saat training, input baru dibuat menjadi DataFrame dengan nama kolom yang sama.

In [10]:
input_data = pd.DataFrame(np.array([[5.1, 3.5, 1.4, 0.2]]), columns=iris.feature_names)
result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)
print('Hasil prediksi untuk input baru adalah:', prediction_label)

Hasil prediksi untuk input baru adalah: ['setosa']


## 2. Prediksi data baru masuk ke species apa: [7.3, 3.8, 4.6, 2.3]

Pada bagian ini dilakukan prediksi terhadap satu data baru yang diberikan pada soal. Model Gaussian Naïve Bayes yang sudah dibuat sebelumnya digunakan untuk menentukan spesies dari data tersebut.

In [11]:
input_data = pd.DataFrame(
    np.array([[7.3, 3.8, 4.6, 2.3]]),
    columns=iris.feature_names
)

result = NB_model.predict(input_data)
prediction_label = lab.inverse_transform(result)

print('Hasil prediksi untuk input baru adalah:', prediction_label)

Hasil prediksi untuk input baru adalah: ['virginica']


Disini dilakukan prediksi terhadap satu data baru menggunakan model Gaussian Naïve Bayes yang sudah dibuat sebelumnya. Data yang digunakan memiliki empat fitur, yaitu sepal length, sepal width, petal length, dan petal width. Dari hasil prediksi, data `[7.3, 3.8, 4.6, 2.3]` diprediksi masuk ke spesies virginica.